# Generated by Django 4.2.3 on 2024-02-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
